version: '3.7'

services:
  ghost:
    image: ghost
    container_name: ghost
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - 2368:2368

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/startup.sh:/docker-entrypoint.d/startup.sh
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - ghost
    entrypoint: ["/bin/sh", "/docker-entrypoint.d/startup.sh"]

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "sleep 10 && certbot certonly --webroot -w /var/www/certbot --agree-tos --no-eff-email --email nextstepassistant96@gmail.com -d neotechnologyiac.zapto.org --noninteractive && docker exec nginx nginx -s reload"
